# Generated by Django 6.0.4 on 2026-04-18 15:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('complete', 'Completed'), ('add', 'Added'), ('update', 'Updated'), ('donate', 'Donated'), ('purchase', 'Purchased')], max_length=20)),
                ('text', models.CharField(max_length=300)),
                ('tag', models.CharField(max_length=40)),
                ('label', models.CharField(max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(max_length=1000)),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('progress', 'In Progress'), ('urgent', 'Urgent'), ('complete', 'Complete')], default='upcoming', max_length=20)),
                ('location', models.CharField(max_length=120)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('tree_goal', models.PositiveIntegerField(default=100)),
                ('trees_planted', models.PositiveIntegerField(default=0)),
                ('user_goal', models.PositiveIntegerField(default=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['status', 'due_date'],
            },
        ),
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trees', models.PositiveIntegerField()),
                ('note', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='core.task')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
