# Generated by Django 6.0.4 on 2026-04-23 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='tree_goal',
        ),
        migrations.RemoveField(
            model_name='task',
            name='trees_planted',
        ),
        migrations.RemoveField(
            model_name='task',
            name='user_goal',
        ),
        migrations.DeleteModel(
            name='Contribution',
        ),
    ]
